name: Kimai Time-Tracking
markdown: redcarpet
relative_permalinks: false
docu_url: http://kimai.github.io/documentation/
forum_url: http://forum.kimai.org/
download_url: /en/download.html
permalink: /blog/:year/:title/