# jekyll
name: Kimai Time-Tracking
markdown: kramdown
relative_permalinks: false
permalink: /blog/:year/:title/

# Kimai specific
docu_url: /documentation/
forum_url: http://forum.kimai.org/
download_url: /download/
issues_url: https://github.com/kimai/kimai/issues
stable_url: https://github.com/kimai/kimai/releases/download/1.2.2/kimai_1.2.2.zip

# jekyll-sitemap
url: https://www.kimai.org

# plugins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap