name: Kimai Time-Tracking
markdown: redcarpet
relative_permalinks: false
docu_url: http://www.kimai.org/documentation/
forum_url: http://forum.kimai.org/
download_url: /en/download.html
permalink: /blog/:year/:title/
gems:
  - jekyll-redirect-from