# jekyll
name: Kimai Time-Tracking
markdown: kramdown
relative_permalinks: false
permalink: /blog/:year/:title/

# Kimai specific
docu_url: /documentation/
forum_url: http://forum.kimai.org/
download_url: /download/
issues_url: https://github.com/kimai/kimai/issues
kimai_version: 1.3.1

# jekyll-sitemap
url: https://www.kimai.org

bing-id: '874E17F27A8EABE9DDAED762FC498BC4'

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old, .gitignore, .git, .idea]

# plugins
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
